// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUUZgl0pfIcYzHSs1Dp_Eh2rcO1vXS5_U',
    appId: '1:809643039019:web:e4f2a0fe7b8dc03c5fcd6e',
    messagingSenderId: '809643039019',
    projectId: 'finalwmp-43477',
    authDomain: 'finalwmp-43477.firebaseapp.com',
    storageBucket: 'finalwmp-43477.firebasestorage.app',
    measurementId: 'G-ZL8S213H94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlEpgMb7Eww2w0wdLtTcYywit6NtOgFo',
    appId: '1:809643039019:android:bd03f7a92643ce6c5fcd6e',
    messagingSenderId: '809643039019',
    projectId: 'finalwmp-43477',
    storageBucket: 'finalwmp-43477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ffWpxboJibeVSZSEkk1MW6X9fobWpVA',
    appId: '1:809643039019:ios:b318e41050255c545fcd6e',
    messagingSenderId: '809643039019',
    projectId: 'finalwmp-43477',
    storageBucket: 'finalwmp-43477.firebasestorage.app',
    iosBundleId: 'com.example.wmp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ffWpxboJibeVSZSEkk1MW6X9fobWpVA',
    appId: '1:809643039019:ios:b318e41050255c545fcd6e',
    messagingSenderId: '809643039019',
    projectId: 'finalwmp-43477',
    storageBucket: 'finalwmp-43477.firebasestorage.app',
    iosBundleId: 'com.example.wmp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUUZgl0pfIcYzHSs1Dp_Eh2rcO1vXS5_U',
    appId: '1:809643039019:web:c69a977f37ade89d5fcd6e',
    messagingSenderId: '809643039019',
    projectId: 'finalwmp-43477',
    authDomain: 'finalwmp-43477.firebaseapp.com',
    storageBucket: 'finalwmp-43477.firebasestorage.app',
    measurementId: 'G-BSFHXZN935',
  );

}